# Generated by Django 3.0.3 on 2020-06-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mails',
        ),
    ]
